name: Random Activity Generator

on:
  schedule:
    - cron: "0 */3 * * *"   # Har 3 ghante baad run hoga
  workflow_dispatch:          # Manual run button

jobs:
  auto-commit:
    permissions:
      contents: write        # Explicit write permission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Random Multiple Commits
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          NUM_COMMITS=$(( ( RANDOM % 8 ) + 1 ))
          echo "Generating $NUM_COMMITS commits..."

          for i in $(seq 1 $NUM_COMMITS); do
            echo "Matrix Activity: $(date) - Loop $i" >> activity.log
            git add activity.log
            git commit -m "chore(matrix): sync log $i" || true
            sleep 1
          done

          git push
